server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

zuul:
  routes:
    user-service:
      path: /api/v1/users/**
      url: http://localhost:8082/users



spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          google-client-1:
            client-id: 429346083756-9b0s12cb66emanu16nf165kdpng3mbur.apps.googleusercontent.com
            client-secret: 5j6LO6pYVfbIWuDPp9PEERrB
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login
            scope: openid,email,profile
            provider: google-client-1
        provider:
          google-client-1:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token

